####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:

  # MySQL Data
  sandbox-mysql-data:
    driver: local

  # Redis Data
  sandbox-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: sandbox-mysql
    networks:
      - teste_uplexis
    volumes:
      - sandbox-mysql-data:/var/lib/mysql
    ports:
      - "3304:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandbox
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: sandbox-redis
    command: --appendonly yes
    networks:
      - teste_uplexis
    volumes:
      - sandbox-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: sandbox-app
    networks:
      - teste_uplexis
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
      - "443:8080"
    links:
      - mysql
      - cache

networks:
  teste_uplexis: